baseURL = "https://eidetic.net.au/urack/"
languageCode = "en-au"
title = "URack"
theme = "book"
pluralizelisttitles = false

pygmentsCodeFences = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
    unsafe = true

[params]
    BookSection = '*'
    BookToc = false

[menu]
[[menu.after]]
    name = "Github"
    url = "https://github.com/eidetic-av"
    weight = 1
[[menu.after]]
    name = "Contact"
    url = "mailto:urack@eidetic.net.au"
    weight = 2
